import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { ConfigService } from '../services/config';
import { RepomixService } from '../services/repomix';
import { AiService } from '../services/ai';
import { TokenService } from '../services/token';
import { GitService } from '../services/git';

const configService = new ConfigService();
const repomixService = new RepomixService();
const aiService = new AiService();
const tokenService = new TokenService();

function getPromptContent(promptPath: string): string {
  const ext = vscode.extensions.getExtension('readme-ai.readme-ai');
  if (!ext) throw new Error('Extension not found');
  const fullPath = path.join(ext.extensionPath, 'src', 'prompts', promptPath);
  return fs.readFileSync(fullPath, 'utf-8');
}

export function registerUpdateCommand(context: vscode.ExtensionContext): vscode.Disposable {
  return vscode.commands.registerCommand('readme-ai.update', async () => {
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    if (!workspaceFolder) {
      vscode.window.showErrorMessage('No workspace folder found');
      return;
    }

    const workspacePath = workspaceFolder.uri.fsPath;

    let config = configService.readIlnskConfig(workspacePath);
    if (!config) {
      config = configService.createIlnskConfig(workspacePath);
      vscode.window.showWarningMessage('Created default .ilnsk config. Please configure and run again.');
      return;
    }

    if (!config.apiUrl || !config.apiKey || !config.model) {
      vscode.window.showWarningMessage('Please configure .ilnsk settings first.');
      vscode.commands.executeCommand('readme-ai.setup');
      return;
    }

    const readmePath = path.join(workspacePath, 'README.md');
    if (!fs.existsSync(readmePath)) {
      vscode.window.showErrorMessage('README.md not found. Generate one first.');
      return;
    }

    const gitService = new GitService(workspacePath);
    const isGitRepo = await gitService.isGitRepository();
    if (!isGitRepo) {
      vscode.window.showErrorMessage('Not a git repository');
      return;
    }

    const currentReadme = fs.readFileSync(readmePath, 'utf-8');

    const hashMatch = currentReadme.match(/<!-- readme-ai:\s*([a-f0-9]+)\s*-->/i);
    if (!hashMatch) {
      vscode.window.showErrorMessage(
        'README.md was not generated by readme-ai. Missing commit hash marker.',
      );
      return;
    }

    const baseRef = hashMatch[1];

    const diff = await gitService.getDiff(baseRef);

    const headHash = await gitService.getLastCommitHash();
    const isUncommitted = headHash === baseRef && diff.hasChanges;

    const allChangedFiles = [
      ...diff.changedFiles,
      ...diff.addedFiles,
      ...diff.deletedFiles,
      ...diff.renamedFiles,
    ];
    const onlyReadmeChanged =
      allChangedFiles.length > 0 &&
      allChangedFiles.every(f => f === 'README.md');

    if (!diff.hasChanges || onlyReadmeChanged || isUncommitted) {
      const action = await vscode.window.showWarningMessage(
        `No code changes detected since ${baseRef.slice(0, 7)}. Force update anyway?`,
        { modal: true },
        'Force Update',
      );
      if (action !== 'Force Update') return;
    }

    vscode.window.showInformationMessage('Running repomix...');
    const outputPath = await repomixService.run(workspacePath);
    let repomixContent = repomixService.readOutput(outputPath);
    repomixContent = repomixContent.replace(
      /<file\s+path="[^"]*README\.md"[^>]*>[\s\S]*?<\/file>\n*/i,
      '',
    );
    repomixContent = repomixContent.replace(/^.*README\.md.*\n/gm, '');
    const tokenCount = tokenService.countForQwen(repomixContent);
    vscode.window.showInformationMessage(`Token count (Qwen): ${tokenCount.toLocaleString()}`);

    const promptContent = getPromptContent('update.md');

    vscode.window.showInformationMessage('Sending to AI...');

    const readmeContent = await aiService.generateReadme(
      config.apiUrl,
      config.apiKey,
      config.model,
      repomixContent,
      promptContent,
    );

    if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath);

    const newCommitHash = await gitService.getLastCommitHash();
    const resultContent = readmeContent.trimEnd() +
      `\n\n<!-- readme-ai: ${newCommitHash || baseRef} -->`;
    fs.writeFileSync(readmePath, resultContent);

    vscode.window.showInformationMessage('README.md updated successfully!');

    const doc = await vscode.workspace.openTextDocument(readmePath);
    await vscode.window.showTextDocument(doc);
  });
}
